<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <RootNamespace>JBC.ExploreTheWorld.AL.BlazorLib</RootNamespace>
    <AssemblyName>JBC.ExploreTheWorld.AL.BlazorLib</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\js\revealio.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Radzen.Blazor" Version="11.1.5" />
    <ProjectReference Include="..\AL\ExploreTheWorld.AL.csproj" />
    <ProjectReference Include="..\BL\ExploreTheWorld.BL.csproj" />
    <ProjectReference Include="..\CL\ExploreTheWorld.CL.csproj" />
    <ProjectReference Include="..\DL.MsJSInterop\ExploreTheWorld.DL.MsJSInterop.csproj" />
    <ProjectReference Include="..\DL.MsJSInterop.RevealJs\ExploreTheWorld.DL.MsJSInterop.RevealJs.csproj" />
    <ProjectReference Include="..\DL\ExploreTheWorld.DL.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.10" />
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
</Project>
