<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>JBC.ExploreTheWorld.DL._netF</AssemblyName>
    <RootNamespace>JBC.ExploreTheWorld.DL</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CL._netF\ExploreTheWorld.CL._netF.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
    <PackageReference Include="System.Text.Json" Version="10.0.10" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Include="..\DL\**\*.cs">
      <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Compile>
  </ItemGroup>
  
  <ItemGroup>
    <Compile Remove="..\DL\obj\**" />
    <Compile Remove="obj\**" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="obj\**" />
  </ItemGroup>

</Project>
