CREATE TABLE [_Template_Link] (
  [GUID] GUID CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [Row_ID] AUTOINCREMENT CONSTRAINT [Row_ID] UNIQUE,
  [Name] VARCHAR (255),
  [Source_GUID] GUID,
  [Target_GUID] GUID,
  [Comment] LONGTEXT,
   CONSTRAINT 
)
