CREATE TABLE [cns_CountryPopulation] (
  [GUID] GUID CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [Row_ID] AUTOINCREMENT CONSTRAINT [Row_ID] UNIQUE,
  [Country] VARCHAR (255),
  [Code] VARCHAR (10),
  [Iso3] VARCHAR (3)
)
