CREATE TABLE [cns_CountryStates] (
  [GUID] GUID CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [Row_ID] AUTOINCREMENT CONSTRAINT [Row_ID] UNIQUE,
  [Name] VARCHAR (255),
  [Iso3] VARCHAR (3)
)
