CREATE TABLE [cns_City] (
  [GUID] GUID CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [Row_ID] AUTOINCREMENT CONSTRAINT [Row_ID] UNIQUE,
  [Iso2] VARCHAR (2) CONSTRAINT [cns_CountryCity] REFERENCES [cns_Country] ([Iso2]),
  [City] VARCHAR (255)
)
