CREATE TABLE [cns_Country] (
  [GUID] GUID CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [Row_ID] AUTOINCREMENT CONSTRAINT [Row_ID] UNIQUE,
  [Iso2] VARCHAR (2) CONSTRAINT [Iso2] UNIQUE,
  [Country] VARCHAR (255),
  [Iso3] VARCHAR (3)
)
