CREATE TABLE [MsOfficeEvents] (
  [GUID] GUID CONSTRAINT [GUID] UNIQUE CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [Row_ID] AUTOINCREMENT CONSTRAINT [Row_ID] UNIQUE,
  [Name] VARCHAR (255) CONSTRAINT [Name] UNIQUE,
  [Category] VARCHAR (255),
  [Word] BIT,
  [Excel] BIT,
  [PowerPoint] BIT,
  [Log] BIT
)
