<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>JBC.ExploreTheWorld.AL.WinFormsLib</AssemblyName>
    <RootNamespace>JBC.ExploreTheWorld.AL.WinFormsLib</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebView.WindowsForms" Version="10.0.80" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\code-zgh-NetOfficeFw__NetOffice__10\Source\Analyzers\NetOffice.Analyzers\NetOffice.Analyzers.csproj" />
    <ProjectReference Include="..\..\..\code-zgh-NetOfficeFw__NetOffice__10\Source\NetOffice\NetOffice.csproj" />
    <ProjectReference Include="..\..\..\code-zgh-NetOfficeFw__NetOffice__10\Source\Office\OfficeApi.csproj" />
    <ProjectReference Include="..\..\..\code-zgh-NetOfficeFw__NetOffice__10\Source\Word\WordApi.csproj" />
    <ProjectReference Include="..\..\..\code-zgh-NetOfficeFw__NetOffice__10\Source\Excel\ExcelApi.csproj" />
    <ProjectReference Include="..\..\..\code-zgh-NetOfficeFw__NetOffice__10\Source\PowerPoint\PowerPointApi.csproj" />
    <ProjectReference Include="..\AL\ExploreTheWorld.AL.csproj" />
    <ProjectReference Include="..\AL.BlazorLib\ExploreTheWorld.AL.BlazorLib.csproj" />
    <ProjectReference Include="..\BL\ExploreTheWorld.BL.csproj" />
    <ProjectReference Include="..\CL\ExploreTheWorld.CL.csproj" />
    <ProjectReference Include="..\DL\ExploreTheWorld.DL.csproj" />
    <ProjectReference Include="..\DL.CountriesNowSpaceApi\ExploreTheWorld.DL.CountriesNowSpaceApi.csproj" />
  </ItemGroup>
</Project>
