<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>JBC.ExploreTheWorld.BL._netF</AssemblyName>
    <RootNamespace>JBC.ExploreTheWorld.BL</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CL._netF\ExploreTheWorld.CL._netF.csproj" />
    <ProjectReference Include="..\DL._netF\ExploreTheWorld.DL._netF.csproj" />    <ProjectReference Include="..\DL.CountriesNowSpaceApi._netF\ExploreTheWorld.DL.CountriesNowSpaceApi._netF.csproj" />  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Net.Http.Json" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\BL\**\*.cs">
      <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="..\BL\obj\**" />
    <Compile Remove="obj\**" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="obj\**" />
  </ItemGroup>

</Project>
