<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>JBC.ExploreTheWorld.RazorTests</AssemblyName>
    <RootNamespace>JBC.ExploreTheWorld.RazorTests</RootNamespace>
    <IsTestProject>true</IsTestProject>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="bunit" Version="2.7.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="FluentAssertions" Version="8.10.0" />
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AL.BlazorLib\ExploreTheWorld.AL.BlazorLib.csproj" />
    <ProjectReference Include="..\..\AL\ExploreTheWorld.AL.csproj" />
    <ProjectReference Include="..\..\BL\ExploreTheWorld.BL.csproj" />
    <ProjectReference Include="..\..\CL\ExploreTheWorld.CL.csproj" />
    <ProjectReference Include="..\..\DL\ExploreTheWorld.DL.csproj" />
    <ProjectReference Include="..\..\DL.CountriesNowSpaceApi\ExploreTheWorld.DL.CountriesNowSpaceApi.csproj" />
    <ProjectReference Include="..\..\DL.MsJSInterop\ExploreTheWorld.DL.MsJSInterop.csproj" />
  </ItemGroup>

</Project>
